package cierrelotedtos

func (mx *EstructuraRegistros) MxTotalesDescripcionRegistro() []EstructuraRegistros {
	registroMxTotales := make([]EstructuraRegistros, 0, 16)
	registroMxTotales = append(registroMxTotales,
		EstructuraRegistros{NombreVariable: "Empresa", Cantidad: 5, Desde: 0, Hasta: 5},
		EstructuraRegistros{NombreVariable: "Fechapres", Cantidad: 6, Desde: 5, Hasta: 11},
		EstructuraRegistros{NombreVariable: "Tiporeg", Cantidad: 2, Desde: 11, Hasta: 13},
		EstructuraRegistros{NombreVariable: "Numcom", Cantidad: 10, Desde: 13, Hasta: 23},
		EstructuraRegistros{NombreVariable: "Numest", Cantidad: 10, Desde: 23, Hasta: 33},
		EstructuraRegistros{NombreVariable: "Codop", Cantidad: 4, Desde: 33, Hasta: 37},
		EstructuraRegistros{NombreVariable: "Tipoaplic", Cantidad: 1, Desde: 37, Hasta: 38},
		EstructuraRegistros{NombreVariable: "Filler", Cantidad: 38, Desde: 38, Hasta: 76},
		EstructuraRegistros{NombreVariable: "Fechapago", Cantidad: 6, Desde: 76, Hasta: 82},
		EstructuraRegistros{NombreVariable: "Libre", Cantidad: 8, Desde: 82, Hasta: 90},
		EstructuraRegistros{NombreVariable: "ImporteTotal", Cantidad: 17, Desde: 90, Hasta: 107},
		EstructuraRegistros{NombreVariable: "SignoImporteTotal", Cantidad: 1, Desde: 107, Hasta: 108},
		EstructuraRegistros{NombreVariable: "Filler1", Cantidad: 25, Desde: 108, Hasta: 133},
		EstructuraRegistros{NombreVariable: "McaPex", Cantidad: 1, Desde: 133, Hasta: 134},
		EstructuraRegistros{NombreVariable: "Filler2", Cantidad: 615, Desde: 134, Hasta: 749},
		EstructuraRegistros{NombreVariable: "Aster", Cantidad: 1, Desde: 749, Hasta: 750},
	)
	return registroMxTotales

}

func (mx *EstructuraRegistros) MxDetalleDescripcionRegistro() []EstructuraRegistros {
	registroMxDetalle := make([]EstructuraRegistros, 0, 16)
	registroMxDetalle = append(registroMxDetalle,
		EstructuraRegistros{NombreVariable: "Empresa", Cantidad: 5, Desde: 0, Hasta: 5},
		EstructuraRegistros{NombreVariable: "Fechapresentacion", Cantidad: 6, Desde: 5, Hasta: 11},
		EstructuraRegistros{NombreVariable: "Tiporeg", Cantidad: 2, Desde: 11, Hasta: 13},
		EstructuraRegistros{NombreVariable: "Numcom", Cantidad: 10, Desde: 13, Hasta: 23},
		EstructuraRegistros{NombreVariable: "Numest", Cantidad: 10, Desde: 23, Hasta: 33},
		EstructuraRegistros{NombreVariable: "Codop", Cantidad: 4, Desde: 33, Hasta: 37},
		EstructuraRegistros{NombreVariable: "Tipoaplic", Cantidad: 1, Desde: 37, Hasta: 38},
		EstructuraRegistros{NombreVariable: "Lote", Cantidad: 4, Desde: 38, Hasta: 42},
		EstructuraRegistros{NombreVariable: "Codbco", Cantidad: 3, Desde: 42, Hasta: 45},
		EstructuraRegistros{NombreVariable: "Codcasa", Cantidad: 3, Desde: 45, Hasta: 48},
		EstructuraRegistros{NombreVariable: "Bcoest", Cantidad: 3, Desde: 48, Hasta: 51},
		EstructuraRegistros{NombreVariable: "Bcocasa", Cantidad: 3, Desde: 51, Hasta: 54},
		EstructuraRegistros{NombreVariable: "Numtar", Cantidad: 16, Desde: 54, Hasta: 70},
		EstructuraRegistros{NombreVariable: "ForigCompra", Cantidad: 6, Desde: 70, Hasta: 76},
		EstructuraRegistros{NombreVariable: "Fechapag", Cantidad: 6, Desde: 76, Hasta: 82},
		EstructuraRegistros{NombreVariable: "Numcomp", Cantidad: 8, Desde: 82, Hasta: 90},
		EstructuraRegistros{NombreVariable: "Importe", Cantidad: 17, Desde: 90, Hasta: 107},
		EstructuraRegistros{NombreVariable: "Signo", Cantidad: 1, Desde: 107, Hasta: 108},
		EstructuraRegistros{NombreVariable: "Numaut", Cantidad: 5, Desde: 108, Hasta: 113},
		EstructuraRegistros{NombreVariable: "Numcuot", Cantidad: 2, Desde: 113, Hasta: 115},
		EstructuraRegistros{NombreVariable: "Plancuot", Cantidad: 2, Desde: 115, Hasta: 117},
		EstructuraRegistros{NombreVariable: "RecAcep", Cantidad: 1, Desde: 117, Hasta: 118},
		EstructuraRegistros{NombreVariable: "RechPrint", Cantidad: 2, Desde: 118, Hasta: 120},
		EstructuraRegistros{NombreVariable: "RechSecun", Cantidad: 2, Desde: 120, Hasta: 122},
		EstructuraRegistros{NombreVariable: "ImpPlan", Cantidad: 17, Desde: 122, Hasta: 139},
		EstructuraRegistros{NombreVariable: "Signo1", Cantidad: 1, Desde: 139, Hasta: 140},
		EstructuraRegistros{NombreVariable: "McaPex", Cantidad: 1, Desde: 140, Hasta: 141},
		EstructuraRegistros{NombreVariable: "Nroliq", Cantidad: 8, Desde: 141, Hasta: 149},
		EstructuraRegistros{NombreVariable: "CcoOrigen", Cantidad: 1, Desde: 149, Hasta: 150},
		EstructuraRegistros{NombreVariable: "CcoMotivo", Cantidad: 2, Desde: 150, Hasta: 152},
		EstructuraRegistros{NombreVariable: "IdCargoliq", Cantidad: 3, Desde: 152, Hasta: 155},
		EstructuraRegistros{NombreVariable: "Moneda", Cantidad: 1, Desde: 155, Hasta: 156},
		EstructuraRegistros{NombreVariable: "PromoBonifUsu", Cantidad: 3, Desde: 156, Hasta: 159},
		EstructuraRegistros{NombreVariable: "PromoBonifEst", Cantidad: 3, Desde: 159, Hasta: 162},
		EstructuraRegistros{NombreVariable: "IdPromo", Cantidad: 1, Desde: 162, Hasta: 163},
		EstructuraRegistros{NombreVariable: "MovImporig", Cantidad: 17, Desde: 163, Hasta: 180},
		EstructuraRegistros{NombreVariable: "SgImporig", Cantidad: 1, Desde: 180, Hasta: 181},
		EstructuraRegistros{NombreVariable: "IdCf", Cantidad: 1, Desde: 181, Hasta: 182},
		EstructuraRegistros{NombreVariable: "CfExentoIva", Cantidad: 1, Desde: 182, Hasta: 183},
		EstructuraRegistros{NombreVariable: "Dealer", Cantidad: 10, Desde: 183, Hasta: 193},
		EstructuraRegistros{NombreVariable: "CuitEst", Cantidad: 11, Desde: 193, Hasta: 204},
		EstructuraRegistros{NombreVariable: "FechapagAjuLqe", Cantidad: 6, Desde: 204, Hasta: 210},
		EstructuraRegistros{NombreVariable: "CodMotivoAjuLqe", Cantidad: 4, Desde: 210, Hasta: 214},
		EstructuraRegistros{NombreVariable: "IdentifNroFactura", Cantidad: 19, Desde: 214, Hasta: 233},
		EstructuraRegistros{NombreVariable: "PorcdtoArancel", Cantidad: 4, Desde: 233, Hasta: 237},
		EstructuraRegistros{NombreVariable: "Arancel", Cantidad: 17, Desde: 237, Hasta: 254},
		EstructuraRegistros{NombreVariable: "SignoArancel", Cantidad: 1, Desde: 254, Hasta: 255},
		EstructuraRegistros{NombreVariable: "TnaCf", Cantidad: 5, Desde: 255, Hasta: 260},
		EstructuraRegistros{NombreVariable: "ImporteCostoFin", Cantidad: 17, Desde: 260, Hasta: 277},
		EstructuraRegistros{NombreVariable: "SigImporteCostoFinanciero", Cantidad: 1, Desde: 277, Hasta: 278},
		EstructuraRegistros{NombreVariable: "IdTx", Cantidad: 6, Desde: 278, Hasta: 284},
		EstructuraRegistros{NombreVariable: "Agencia", Cantidad: 1, Desde: 284, Hasta: 285},
		EstructuraRegistros{NombreVariable: "TipoPlan", Cantidad: 1, Desde: 285, Hasta: 286},
		EstructuraRegistros{NombreVariable: "BanderaEst", Cantidad: 3, Desde: 286, Hasta: 289},
		EstructuraRegistros{NombreVariable: "Subcodigo", Cantidad: 2, Desde: 289, Hasta: 291},
		EstructuraRegistros{NombreVariable: "Filler", Cantidad: 3, Desde: 291, Hasta: 294},
		EstructuraRegistros{NombreVariable: "CcoMotivoMc", Cantidad: 4, Desde: 294, Hasta: 298},
		EstructuraRegistros{NombreVariable: "NumtarXl", Cantidad: 19, Desde: 298, Hasta: 317},
		EstructuraRegistros{NombreVariable: "NumautXl", Cantidad: 8, Desde: 317, Hasta: 325},
		EstructuraRegistros{NombreVariable: "Filler1", Cantidad: 424, Desde: 325, Hasta: 749}, // 432
		EstructuraRegistros{NombreVariable: "IdFinRegistro", Cantidad: 1, Desde: 749, Hasta: 750},
	)
	return registroMxDetalle
}
