package cierrelotedtos

type EstructuraRegistros struct {
	NombreVariable string
	Cantidad       int
	Desde          int
	Hasta          int
}

func (px *EstructuraRegistros) PxDosDescripcionRegistro() []EstructuraRegistros {
	registroPxDos := make([]EstructuraRegistros, 0, 77)
	registroPxDos = append(registroPxDos,

		EstructuraRegistros{NombreVariable: "ECLQ02LL-EMPRESA", Cantidad: 5, Desde: 0, Hasta: 5},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-FPRES", Cantidad: 6, Desde: 5, Hasta: 11},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-TIPOREG", Cantidad: 2, Desde: 11, Hasta: 13},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-MONEDA", Cantidad: 3, Desde: 13, Hasta: 16},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-NUMCOM", Cantidad: 10, Desde: 16, Hasta: 26},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-NUMEST", Cantidad: 10, Desde: 26, Hasta: 36},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-NROLIQ", Cantidad: 8, Desde: 36, Hasta: 44},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-FPAG.", Cantidad: 6, Desde: 44, Hasta: 50},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-TIPOLIQ", Cantidad: 1, Desde: 50, Hasta: 51},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IMPBRUTO", Cantidad: 18, Desde: 51, Hasta: 69},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-1", Cantidad: 1, Desde: 69, Hasta: 70},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IMPRET", Cantidad: 15, Desde: 70, Hasta: 85},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-2", Cantidad: 1, Desde: 85, Hasta: 86},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IMPNETO", Cantidad: 18, Desde: 86, Hasta: 104},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-3", Cantidad: 1, Desde: 104, Hasta: 105},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RETESP", Cantidad: 15, Desde: 105, Hasta: 120},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-4", Cantidad: 1, Desde: 120, Hasta: 121},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RETIVA-ESP", Cantidad: 15, Desde: 121, Hasta: 136},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-5", Cantidad: 1, Desde: 136, Hasta: 137},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-PERCEP-BA", Cantidad: 17, Desde: 137, Hasta: 154},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-6", Cantidad: 1, Desde: 154, Hasta: 155},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RETIVA-D1", Cantidad: 15, Desde: 155, Hasta: 170},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-7", Cantidad: 1, Desde: 170, Hasta: 171},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 15, Desde: 171, Hasta: 186},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 186, Hasta: 187},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CARGO-PEX", Cantidad: 17, Desde: 187, Hasta: 204},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-9", Cantidad: 1, Desde: 204, Hasta: 205},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RETIVA-PEX1", Cantidad: 17, Desde: 205, Hasta: 222},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-10", Cantidad: 1, Desde: 222, Hasta: 223},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 17, Desde: 223, Hasta: 240},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 240, Hasta: 241},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-COSTO-CUOEMI", Cantidad: 17, Desde: 241, Hasta: 258},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-12", Cantidad: 1, Desde: 258, Hasta: 259},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RETIVA-CUO1", Cantidad: 17, Desde: 259, Hasta: 276},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-13", Cantidad: 1, Desde: 276, Hasta: 277},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 17, Desde: 277, Hasta: 294},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 294, Hasta: 295},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IMP-SERV", Cantidad: 15, Desde: 295, Hasta: 310},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-15", Cantidad: 1, Desde: 310, Hasta: 311},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-XLJ", Cantidad: 17, Desde: 311, Hasta: 328},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-16", Cantidad: 1, Desde: 328, Hasta: 329},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 17, Desde: 329, Hasta: 346},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 346, Hasta: 347},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CARGO-EDC-E", Cantidad: 15, Desde: 347, Hasta: 362},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-18", Cantidad: 1, Desde: 362, Hasta: 363},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-EDC-E", Cantidad: 15, Desde: 363, Hasta: 378},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-19", Cantidad: 1, Desde: 378, Hasta: 379},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 15, Desde: 379, Hasta: 394},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 394, Hasta: 395},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CARGO-EDC-B", Cantidad: 15, Desde: 395, Hasta: 410},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-21", Cantidad: 1, Desde: 410, Hasta: 411},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-EDC-B", Cantidad: 15, Desde: 411, Hasta: 426},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-22", Cantidad: 1, Desde: 426, Hasta: 427},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 15, Desde: 427, Hasta: 442},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 442, Hasta: 443},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CARGO-CIT-E", Cantidad: 17, Desde: 443, Hasta: 460},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-24", Cantidad: 1, Desde: 460, Hasta: 461},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-CIT-E", Cantidad: 17, Desde: 461, Hasta: 478},
		EstructuraRegistros{NombreVariable: "ECLQ02LLLL-SIGNO-25", Cantidad: 1, Desde: 478, Hasta: 479},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 17, Desde: 479, Hasta: 496},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 496, Hasta: 497},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CARGO-CIT-B", Cantidad: 17, Desde: 497, Hasta: 514},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-27", Cantidad: 1, Desde: 514, Hasta: 515},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-CIT-B", Cantidad: 17, Desde: 515, Hasta: 532},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-28", Cantidad: 1, Desde: 532, Hasta: 533},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 17, Desde: 533, Hasta: 550},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 550, Hasta: 551},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RET-IVA", Cantidad: 15, Desde: 551, Hasta: 566},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-30", Cantidad: 1, Desde: 566, Hasta: 567},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RET-GCIAS", Cantidad: 15, Desde: 567, Hasta: 582},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-31", Cantidad: 1, Desde: 582, Hasta: 583},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RET-INGBRU", Cantidad: 15, Desde: 583, Hasta: 598},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-32", Cantidad: 1, Desde: 598, Hasta: 599},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 7, Desde: 599, Hasta: 606},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 606, Hasta: 607},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 92, Desde: 607, Hasta: 699},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ASTER", Cantidad: 1, Desde: 699, Hasta: 700})
	return registroPxDos
}

func (px *EstructuraRegistros) PxCuatroDescripcionRegistro() []EstructuraRegistros {
	registroPxCuatro := make([]EstructuraRegistros, 0, 93)
	registroPxCuatro = append(registroPxCuatro,
		EstructuraRegistros{NombreVariable: "ECLQ02LL-EMPRESA-04", Cantidad: 5, Desde: 0, Hasta: 5},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-FPRES-04", Cantidad: 6, Desde: 5, Hasta: 11},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-TIPOREG-04", Cantidad: 2, Desde: 11, Hasta: 13},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-MONEDA-04", Cantidad: 3, Desde: 13, Hasta: 16},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-NUMCOM-04", Cantidad: 10, Desde: 16, Hasta: 26},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-NUMEST-04", Cantidad: 10, Desde: 26, Hasta: 36},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-NROLIQ-04", Cantidad: 8, Desde: 36, Hasta: 44},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-FPAG-04.", Cantidad: 6, Desde: 44, Hasta: 50},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-TIPOLIQ-04", Cantidad: 1, Desde: 50, Hasta: 51},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CASACTA", Cantidad: 3, Desde: 51, Hasta: 54},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-TIPCTA", Cantidad: 2, Desde: 54, Hasta: 56},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CTABCO", Cantidad: 15, Desde: 56, Hasta: 71},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CF-EXENTO-IVA", Cantidad: 17, Desde: 71, Hasta: 88},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-1", Cantidad: 1, Desde: 88, Hasta: 89},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-LEY25063", Cantidad: 17, Desde: 89, Hasta: 106},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-2", Cantidad: 1, Desde: 106, Hasta: 107},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ALI-INGBRU", Cantidad: 5, Desde: 107, Hasta: 112},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-DTO-CAMPANIA", Cantidad: 17, Desde: 112, Hasta: 129},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-3", Cantidad: 1, Desde: 129, Hasta: 130},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-DTO-CAMPANIA", Cantidad: 17, Desde: 130, Hasta: 147},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-4", Cantidad: 1, Desde: 147, Hasta: 148},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RET-INGBRU2", Cantidad: 17, Desde: 148, Hasta: 165},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-5", Cantidad: 1, Desde: 165, Hasta: 166},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ALI-INGBRU2", Cantidad: 5, Desde: 166, Hasta: 171},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 17, Desde: 171, Hasta: 188},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 188, Hasta: 189},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 17, Desde: 189, Hasta: 206},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 206, Hasta: 207},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 3, Desde: 207, Hasta: 210},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-TASA-PEX", Cantidad: 8, Desde: 210, Hasta: 218},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CARGO-X-LIQ", Cantidad: 7, Desde: 218, Hasta: 225},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-8", Cantidad: 1, Desde: 225, Hasta: 226},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-CARGO-X-LIQ", Cantidad: 7, Desde: 226, Hasta: 233},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-9", Cantidad: 1, Desde: 233, Hasta: 234},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-DEALER", Cantidad: 10, Desde: 234, Hasta: 244},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IMP-DB-CR", Cantidad: 17, Desde: 244, Hasta: 261},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-10", Cantidad: 1, Desde: 261, Hasta: 262},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-CF-NO-REDUCE-IVA", Cantidad: 17, Desde: 262, Hasta: 279},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-11", Cantidad: 1, Desde: 279, Hasta: 280},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-PERCEP-IB-AGIP", Cantidad: 17, Desde: 280, Hasta: 297},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-12", Cantidad: 1, Desde: 297, Hasta: 298},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ALIC-PERCEP-IB-AGIP", Cantidad: 4, Desde: 298, Hasta: 302},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RETEN-IB-AGIP", Cantidad: 17, Desde: 302, Hasta: 319},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-13", Cantidad: 1, Desde: 319, Hasta: 320},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ALIC-RETEN-IB-AGIP", Cantidad: 4, Desde: 320, Hasta: 324},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SUBTOT-RETIVA-RG3130", Cantidad: 17, Desde: 324, Hasta: 341},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-14", Cantidad: 1, Desde: 341, Hasta: 342},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-PROV-INGBRU", Cantidad: 1, Desde: 342, Hasta: 343},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ADIC-PLANCUO", Cantidad: 17, Desde: 343, Hasta: 360},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-15", Cantidad: 1, Desde: 360, Hasta: 361},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-AD-PLANCUO", Cantidad: 17, Desde: 361, Hasta: 378},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-16", Cantidad: 1, Desde: 378, Hasta: 379},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ADIC-OPINTER", Cantidad: 17, Desde: 379, Hasta: 396},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-17", Cantidad: 1, Desde: 396, Hasta: 397},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-AD-OPINTER", Cantidad: 17, Desde: 397, Hasta: 414},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-18", Cantidad: 1, Desde: 414, Hasta: 415},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ADIC-ALTACOM", Cantidad: 17, Desde: 415, Hasta: 432},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-19", Cantidad: 1, Desde: 432, Hasta: 433},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-AD-ALTACOM", Cantidad: 17, Desde: 433, Hasta: 450},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-20", Cantidad: 1, Desde: 450, Hasta: 451},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ADIC-CUPMANU", Cantidad: 17, Desde: 451, Hasta: 468},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-21", Cantidad: 1, Desde: 468, Hasta: 469},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-AD-CUPMANU", Cantidad: 17, Desde: 469, Hasta: 486},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-22", Cantidad: 1, Desde: 486, Hasta: 487},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ADIC-ALTACOM-BCO", Cantidad: 17, Desde: 487, Hasta: 504},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-23", Cantidad: 1, Desde: 504, Hasta: 505},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-AD-ALTACOM-BCO", Cantidad: 17, Desde: 505, Hasta: 522},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-24", Cantidad: 1, Desde: 522, Hasta: 523},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 17, Desde: 523, Hasta: 540},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 540, Hasta: 541},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 17, Desde: 541, Hasta: 558},
		EstructuraRegistros{NombreVariable: "FILLER", Cantidad: 1, Desde: 558, Hasta: 559},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ADIC-MOVYPAG", Cantidad: 17, Desde: 559, Hasta: 576},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-27", Cantidad: 1, Desde: 576, Hasta: 577},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-IVA1-ADIC-MOVYPAG", Cantidad: 17, Desde: 577, Hasta: 594},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-28", Cantidad: 1, Desde: 595, Hasta: 596},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RET-SELLOS", Cantidad: 16, Desde: 596, Hasta: 612}, //17
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-29", Cantidad: 1, Desde: 612, Hasta: 613},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-PROV-SELLOS", Cantidad: 1, Desde: 613, Hasta: 614},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RET-INGBRU3", Cantidad: 17, Desde: 614, Hasta: 631},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-30", Cantidad: 1, Desde: 632, Hasta: 633},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ALI-INGBRU3", Cantidad: 5, Desde: 633, Hasta: 638},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RET-INGBRU4", Cantidad: 10, Desde: 638, Hasta: 648}, //11
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-31", Cantidad: 1, Desde: 648, Hasta: 649},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ALI-INGBRU4", Cantidad: 5, Desde: 649, Hasta: 654},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RET-INGBRU5", Cantidad: 11, Desde: 654, Hasta: 665},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-32", Cantidad: 1, Desde: 665, Hasta: 666},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ALI-INGBRU5", Cantidad: 5, Desde: 666, Hasta: 671},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-RET-INGBRU6", Cantidad: 11, Desde: 671, Hasta: 682},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-SIGNO-04-33", Cantidad: 1, Desde: 682, Hasta: 683},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ALI-INGBRU6", Cantidad: 5, Desde: 683, Hasta: 688},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-FILLER-04", Cantidad: 11, Desde: 688, Hasta: 699},
		EstructuraRegistros{NombreVariable: "ECLQ02LL-ASTER-04", Cantidad: 1, Desde: 699, Hasta: 700},
	)
	return registroPxCuatro
}
