package prismadtos

const ERROR_ESTRUCTURA_INCORRECTA = "los datos recibidos son incorrectos"
const ERROR_NUMBER_CARD = "el número de tarjeta no es válido"
const ERROR_DATE_CARD = "la fecha de vencimiento de la tarjeta es inválida"
const ERROR_HOLDER_NAME = "nombre no válido"
const ERROR_SECURITYCODE = "longitud del código de seguridad incorrecto"
const ERROR_SITE_TRANSACTION_ID = "el número de transacción es incorrecto"
const ERROR_TOKEN_PAGO = "token de pago no válido"
const ERROR_BIN = "el número de tarjeta no es válido, verifique los seis primeros dígitos"
const ERROR_AMOUNT = "el monto ingresado no es válido"
const ERROR_CURRENCY = "la moneda seleccionada no es válida"
const ERROR_INSTALLMENTS = "el esquema de cuotas seleccionado es incorrecto"
const ERROR_PAYMENT_TYPE = "el tipo de pago seleccionado es incorrecto"
const ERROR_ESTABLISHMENT_NAME = "el número de caracteres es superior a 25 o posee caracter no permitido"
const ERROR_NRO_DOC = "el número de documento ingresado no es válido"
const ERRR_TIPO_PAGO = "el tipo de pago seleccionado no es válido"
const ERROR_EMAIL = "el correo electrónico ingresado no es válido"
const ERROR_MODO_PAGO = "el modo de pago seleccionado no es válido"
const ERROR_SURCHANGE = "el valor ingresado no es válido"
const ERROR_CODP3 = "el indicador de los días que existen entre el 1er y 2do vencimiento no son válidos"
const ERROR_CODP4 = "el indicador de los días después del 1º vencimiento y hasta el que el cliente puede pagar no es válido"
const ERROR_CLIENTE_NRO = "el número de cliente no es válido"
const ERROR_NOMBRE_ESTABLECIMIENTO = "el nombre de establecimiento ingresado no es válido"
const ERROR_NOMBRE_PAGADOR = "debe ingresar su nombre"
const ERROR_TIPO_DOCUMENTO = "tipo de documento seleccionado no válido"
